POST http://localhost:3005/api/sendMail
Content-Type: application/json

{
    "from": "testFrom",
    "to": "testTo",
    "subject": "It worked!",
    "text": "incredible",
    "html": "<b>incredible</b>"
}

###
